wandb_version: 1

batch_size:
  value: 32
beam_size:
  value: 5
cell_type:
  value: RNN
dec_layers:
  value: 2
dropout:
  value: 0.3
embedding_size:
  value: 64
enc_layers:
  value: 3
hidden_size:
  value: 32
learning_rate:
  value: 0.001
