wandb_version: 1

batch_size:
  value: 64
beam_size:
  value: 5
cell_type:
  value: lstm
dec_layers:
  value: 2
dropout:
  value: 0.2
embed:
  value: 32
enc_layers:
  value: 2
hidden:
  value: 256
learning_rate:
  value: 0.001
