wandb_version: 1

batch_size:
  value: 64
beam_size:
  value: 3
cell_type:
  value: lstm
dec_layers:
  value: 3
dropout:
  value: 0.2
embed:
  value: 32
enc_layers:
  value: 3
hidden:
  value: 128
learning_rate:
  value: 0.001
