wandb_version: 1

batch_size:
  value: 32
beam_size:
  value: 1
cell_type:
  value: lstm
dec_layers:
  value: 2
dropout:
  value: 0.2
embed:
  value: 128
enc_layers:
  value: 1
hidden:
  value: 256
learning_rate:
  value: 0.0001
