wandb_version: 1

batch_size:
  value: 32
beam_size:
  value: 5
cell_type:
  value: rnn
dec_layers:
  value: 2
dropout:
  value: 0.2
embed:
  value: 16
enc_layers:
  value: 1
hidden:
  value: 256
learning_rate:
  value: 0.0001
