wandb_version: 1

batch_size:
  value: 32
beam_size:
  value: 5
cell_type:
  value: lstm
dec_layers:
  value: 1
dropout:
  value: 0.3
embed:
  value: 128
enc_layers:
  value: 1
hidden:
  value: 64
learning_rate:
  value: 0.001
